apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-time-app

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: flask-time-app

  template:
    metadata:
      labels:
        app: flask-time-app

    spec:
      containers:
        - name: flask-time-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}